package com.example.nlp_project

data class Region(val name: String, val subregions: List<Region> = emptyList())

val regions = listOf(
    Region(
        "강원특별자치도",
        listOf(
            Region("고성군"),
            Region("영월군"),
            Region("인제군"),
            Region("정선군"),
            Region("태백시"),
            Region("평창군"),
            Region("화천군"),
            Region("횡성군")
        )
    ),
    Region(
        "강원특별자치도교육청"
    ),
    Region(
        "경기도",
        listOf(
            Region("고양시"),
            Region("과천시"),
            Region("광주시"),
            Region("군포시"),
            Region("동두천시"),
            Region("부천시"),
            Region("성남시"),
            Region("수원시"),
            Region("시흥시"),
            Region("안산시"),
            Region("안성시"),
            Region("안양시"),
            Region("양평군"),
            Region("여주시"),
            Region("이천시"),
            Region("평택시")
        )
    ),
    Region(
        "경상남도",
        listOf(
            Region("거제시"),
            Region("거창군"),
            Region("김해시"),
            Region("남해군"),
            Region("산청군"),
            Region("창녕군"),
            Region("통영시"),
            Region("하동군"),
            Region("함안군"),
            Region("함양군"),
            Region("합천군")
        )
    ),
    Region(
        "경상북도",
        listOf(
            Region("경산시"),
            Region("문경시"),
            Region("봉화군"),
            Region("상주시"),
            Region("성주군"),
            Region("영천시"),
            Region("울진군"),
            Region("의성군"),
            Region("청송군"),
            Region("포항시")
        )
    ),
    Region(
        "공공기관",
        listOf() // No subregions
    ),
    Region(
        "광주광역시",
        listOf(
            Region("남구"),
            Region("서구")
        )
    ),
    Region(
        "대구광역시",
        listOf(
            Region("군위군"),
            Region("남구"),
            Region("달서구"),
            Region("달성군"),
            Region("서구")
        )
    ),
    Region(
        "대전광역시",
        listOf() // No subregions
    ),
    Region(
        "부산광역시",
        listOf(
            Region("북구"),
            Region("사하구"),
            Region("수영구")
        )
    ),
    Region(
        "서울특별시",
        listOf(
            Region("강남구"),
            Region("강동구"),
            Region("강서구"),
            Region("관악구"),
            Region("광진구"),
            Region("구로구"),
            Region("동작구"),
            Region("마포구"),
            Region("서대문구"),
            Region("서초구"),
            Region("용산구"),
            Region("은평구"),
            Region("중구")
        )
    ),
    Region(
        "세종특별자치시",
        listOf() // No subregions
    ),
    Region(
        "울산광역시",
        listOf(
            Region("남구")
        )
    ),
    Region(
        "인천광역시",
        listOf(
            Region("강화군"),
            Region("계양구"),
            Region("동구"),
            Region("서구"),
            Region("연수구")
        )
    ),
    Region(
        "전라남도",
        listOf(
            Region("강진군"),
            Region("곡성군"),
            Region("광양시"),
            Region("나주시"),
            Region("담양군"),
            Region("무안군"),
            Region("보성군"),
            Region("영광군"),
            Region("영암군"),
            Region("장성군"),
            Region("함평군"),
            Region("해남군"),
            Region("화순군")
        )
    ),
    Region(
        "전북특별자치도",
        listOf(
            Region("김제시"),
            Region("부안군"),
            Region("순창군"),
            Region("완주군"),
            Region("익산시"),
            Region("임실군"),
            Region("전주시")
        )
    ),
    Region(
        "제주특별자치도",
        listOf() // No subregions
    ),
    Region(
        "중앙부처",
        listOf() // No subregions
    ),
    Region(
        "충청남도",
        listOf(
            Region("계룡시"),
            Region("공주시"),
            Region("금산군"),
            Region("논산시"),
            Region("당진시"),
            Region("보령시"),
            Region("부여군"),
            Region("서산시"),
            Region("아산시"),
            Region("예산군"),
            Region("천안시"),
            Region("청양군"),
            Region("태안군"),
            Region("홍성군")
        )
    ),
    Region(
        "충청북도",
        listOf(
            Region("보은군"),
            Region("영동군"),
            Region("옥천군"),
            Region("음성군"),
            Region("증평군"),
            Region("진천군"),
            Region("청주시"),
            Region("충주시")
        )
    )
)